# Generated by Django 2.0.7 on 2018-07-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_Platters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dinner_platters', models.CharField(max_length=32)),
                ('small', models.DecimalField(decimal_places=2, max_digits=4)),
                ('large', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pasta', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Regular_Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pizza', models.CharField(max_length=16)),
                ('small', models.DecimalField(decimal_places=2, max_digits=4)),
                ('large', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sicilian_Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pizza', models.CharField(max_length=16)),
                ('small', models.DecimalField(decimal_places=2, max_digits=4)),
                ('large', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_subs', models.CharField(max_length=64)),
                ('small', models.DecimalField(decimal_places=2, max_digits=4)),
                ('large', models.DecimalField(decimal_places=2, max_digits=4)),
                ('small_cheese', models.DecimalField(decimal_places=2, max_digits=4)),
                ('large_cheese', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
