# Generated by Django 2.0.7 on 2018-08-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180801_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='subs',
            name='small_cheese',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
