# Generated by Django 2.0.7 on 2018-08-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='toppings',
        ),
    ]
