# Generated by Django 2.0.7 on 2018-08-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orders_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platters',
            name='topping',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='toppings',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='topping',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='topping',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salads',
            name='topping',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='topping',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subs',
            name='topping',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
